DETAILED_TICKET_ATTRIBUTES = [
    "id",
    "subject",
    "requester_id",
    "assignee_id",
    "created_at",
    "description",
    "priority",
    "status",
]

SUMMARY_TICKET_ATTRIBUTES = [
    "id",
    "subject",
    "requester_id",
    "assignee_id",
]

PAGINATION_SIZE = {"page[size]": 25}

MOCK_API_RESPONSE_DATA = [
    {
        "url": "https://soontobeintern.zendesk.com/api/v2/tickets/1.json",
        "id": 1,
        "external_id": None,
        "via": {
            "channel": "sample_ticket",
            "source": {"from": {}, "to": {}, "rel": None},
        },
        "created_at": "2021-05-04T04:31:24Z",
        "updated_at": "2021-05-04T04:31:25Z",
        "type": "incident",
        "subject": "Sample ticket: Meet the ticket",
        "raw_subject": "Sample ticket: Meet the ticket",
        "description": "Hi Yonnas,\n\nThis is your first ticket. Ta-da! Any customer request sent to your supported channels (email, chat, voicemail, web form, and tweet) will become a Support ticket, just like this one. Respond to this ticket by typing a message and clicking Submit. You can also see how an email becomes a ticket by emailing your new account, support@soontobeintern.zendesk.com. Your ticket will appear in ticket views.\n\nThat's the ticket on tickets. If you want to learn more, check out: \nhttps://support.zendesk.com/hc/en-us/articles/203691476\n",
        "priority": "normal",
        "status": "open",
        "recipient": None,
        "requester_id": 361109274416,
        "submitter_id": 361109274056,
        "assignee_id": 361109274056,
        "organization_id": None,
        "group_id": 360004927316,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": ["sample", "support", "zendesk"],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "followup_ids": [],
        "ticket_form_id": 360005563896,
        "brand_id": 360000535196,
        "allow_channelback": False,
        "allow_attachments": True,
    },
    {
        "url": "https://soontobeintern.zendesk.com/api/v2/tickets/2.json",
        "id": 2,
        "external_id": None,
        "via": {"channel": "api", "source": {"from": {}, "to": {}, "rel": None}},
        "created_at": "2021-05-04T05:02:51Z",
        "updated_at": "2021-05-04T05:02:51Z",
        "type": None,
        "subject": "velit eiusmod reprehenderit officia cupidatat",
        "raw_subject": "velit eiusmod reprehenderit officia cupidatat",
        "description": "Aute ex sunt culpa ex ea esse sint cupidatat aliqua ex consequat sit reprehenderit. Velit labore proident quis culpa ad duis adipisicing laboris voluptate velit incididunt minim consequat nulla. Laboris adipisicing reprehenderit minim tempor officia ullamco occaecat ut laborum.\n\nAliquip velit adipisicing exercitation irure aliqua qui. Commodo eu laborum cillum nostrud eu. Mollit duis qui non ea deserunt est est et officia ut excepteur Lorem pariatur deserunt.",
        "priority": None,
        "status": "open",
        "recipient": None,
        "requester_id": 361109274056,
        "submitter_id": 361109274056,
        "assignee_id": 361109274056,
        "organization_id": 360039306396,
        "group_id": 360004927316,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": ["est", "incididunt", "nisi"],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "followup_ids": [],
        "ticket_form_id": 360005563896,
        "brand_id": 360000535196,
        "allow_channelback": False,
        "allow_attachments": True,
    },
    {
        "url": "https://soontobeintern.zendesk.com/api/v2/tickets/1.json",
        "id": 1,
        "external_id": None,
        "via": {
            "channel": "sample_ticket",
            "source": {"from": {}, "to": {}, "rel": None},
        },
        "created_at": "2021-05-04T04:31:24Z",
        "updated_at": "2021-05-04T04:31:25Z",
        "type": "incident",
        "subject": "Sample ticket: Meet the ticket",
        "raw_subject": "Sample ticket: Meet the ticket",
        "description": "Hi Yonnas,\n\nThis is your first ticket. Ta-da! Any customer request sent to your supported channels (email, chat, voicemail, web form, and tweet) will become a Support ticket, just like this one. Respond to this ticket by typing a message and clicking Submit. You can also see how an email becomes a ticket by emailing your new account, support@soontobeintern.zendesk.com. Your ticket will appear in ticket views.\n\nThat's the ticket on tickets. If you want to learn more, check out: \nhttps://support.zendesk.com/hc/en-us/articles/203691476\n",
        "priority": "normal",
        "status": "open",
        "recipient": None,
        "requester_id": 361109274416,
        "submitter_id": 361109274056,
        "assignee_id": 361109274056,
        "organization_id": None,
        "group_id": 360004927316,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": ["sample", "support", "zendesk"],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "followup_ids": [],
        "ticket_form_id": 360005563896,
        "brand_id": 360000535196,
        "allow_channelback": False,
        "allow_attachments": True,
    },
    {
        "url": "https://soontobeintern.zendesk.com/api/v2/tickets/2.json",
        "id": 2,
        "external_id": None,
        "via": {"channel": "api", "source": {"from": {}, "to": {}, "rel": None}},
        "created_at": "2021-05-04T05:02:51Z",
        "updated_at": "2021-05-04T05:02:51Z",
        "type": None,
        "subject": "velit eiusmod reprehenderit officia cupidatat",
        "raw_subject": "velit eiusmod reprehenderit officia cupidatat",
        "description": "Aute ex sunt culpa ex ea esse sint cupidatat aliqua ex consequat sit reprehenderit. Velit labore proident quis culpa ad duis adipisicing laboris voluptate velit incididunt minim consequat nulla. Laboris adipisicing reprehenderit minim tempor officia ullamco occaecat ut laborum.\n\nAliquip velit adipisicing exercitation irure aliqua qui. Commodo eu laborum cillum nostrud eu. Mollit duis qui non ea deserunt est est et officia ut excepteur Lorem pariatur deserunt.",
        "priority": None,
        "status": "open",
        "recipient": None,
        "requester_id": 361109274056,
        "submitter_id": 361109274056,
        "assignee_id": 361109274056,
        "organization_id": 360039306396,
        "group_id": 360004927316,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": ["est", "incididunt", "nisi"],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "followup_ids": [],
        "ticket_form_id": 360005563896,
        "brand_id": 360000535196,
        "allow_channelback": False,
        "allow_attachments": True,
    },
    {
        "url": "https://soontobeintern.zendesk.com/api/v2/tickets/3.json",
        "id": 3,
        "external_id": None,
        "via": {"channel": "api", "source": {"from": {}, "to": {}, "rel": None}},
        "created_at": "2021-05-04T05:02:52Z",
        "updated_at": "2021-05-04T05:02:52Z",
        "type": None,
        "subject": "excepteur laborum ex occaecat Lorem",
        "raw_subject": "excepteur laborum ex occaecat Lorem",
        "description": "Exercitation amet in laborum minim. Nulla et veniam laboris dolore fugiat aliqua et sit mollit. Dolor proident nulla mollit culpa in officia pariatur officia magna eu commodo duis.\n\nAliqua reprehenderit aute qui voluptate dolor deserunt enim aute tempor ad dolor fugiat. Mollit aliquip elit aliqua eiusmod. Ex et anim non exercitation consequat elit dolore excepteur. Aliqua reprehenderit non culpa sit consequat cupidatat elit.",
        "priority": None,
        "status": "open",
        "recipient": None,
        "requester_id": 361109274056,
        "submitter_id": 361109274056,
        "assignee_id": 361109274056,
        "organization_id": 360039306396,
        "group_id": 360004927316,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": ["amet", "labore", "voluptate"],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "followup_ids": [],
        "ticket_form_id": 360005563896,
        "brand_id": 360000535196,
        "allow_channelback": False,
        "allow_attachments": True,
    },
    {
        "url": "https://soontobeintern.zendesk.com/api/v2/tickets/4.json",
        "id": 4,
        "external_id": None,
        "via": {"channel": "api", "source": {"from": {}, "to": {}, "rel": None}},
        "created_at": "2021-05-04T05:02:52Z",
        "updated_at": "2021-05-04T05:02:52Z",
        "type": None,
        "subject": "ad sunt qui aute ullamco",
        "raw_subject": "ad sunt qui aute ullamco",
        "description": "Sunt incididunt officia proident elit anim ullamco reprehenderit ut. Aliqua sint amet aliquip cillum minim magna consequat excepteur fugiat exercitation est exercitation. Adipisicing occaecat nisi aliqua exercitation.\n\nAute Lorem aute tempor sunt mollit dolor in consequat non cillum irure reprehenderit. Nulla deserunt qui aliquip officia duis incididunt et est velit nulla irure in fugiat in. Deserunt proident est in dolore culpa mollit exercitation ea anim consequat incididunt. Mollit et occaecat ullamco ut id incididunt laboris occaecat qui.",
        "priority": None,
        "status": "open",
        "recipient": None,
        "requester_id": 361109274056,
        "submitter_id": 361109274056,
        "assignee_id": 361109274056,
        "organization_id": 360039306396,
        "group_id": 360004927316,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": ["laborum", "mollit", "proident"],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "followup_ids": [],
        "ticket_form_id": 360005563896,
        "brand_id": 360000535196,
        "allow_channelback": False,
        "allow_attachments": True,
    },
    {
        "url": "https://soontobeintern.zendesk.com/api/v2/tickets/5.json",
        "id": 5,
        "external_id": None,
        "via": {"channel": "api", "source": {"from": {}, "to": {}, "rel": None}},
        "created_at": "2021-05-04T05:02:53Z",
        "updated_at": "2021-05-04T05:02:53Z",
        "type": None,
        "subject": "aliquip mollit quis laborum incididunt",
        "raw_subject": "aliquip mollit quis laborum incididunt",
        "description": "Pariatur voluptate laborum voluptate sunt ad magna exercitation nulla. In in Lorem minim dolor laboris reprehenderit ad Lorem. Cupidatat laborum qui mollit nostrud magna ullamco. Tempor nisi ex ipsum fugiat dolor proident qui consectetur anim sunt. Dolore consectetur in ex esse et aliqua fugiat enim Lorem ea Lorem incididunt. Non amet elit pariatur commodo labore officia esse anim. In do mollit commodo nulla ullamco culpa cillum incididunt.\n\nEt nostrud aute fugiat voluptate tempor ad labore in elit et sunt. Enim quis nulla eu ut sit. Pariatur irure officia occaecat non dolor est excepteur anim incididunt commodo ea cupidatat minim excepteur. Cillum proident tempor laborum amet est ipsum ipsum aliqua sit sunt reprehenderit fugiat aliqua ea.",
        "priority": None,
        "status": "open",
        "recipient": None,
        "requester_id": 361109274056,
        "submitter_id": 361109274056,
        "assignee_id": 361109274056,
        "organization_id": 360039306396,
        "group_id": 360004927316,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": ["consectetur", "mollit", "sit"],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "followup_ids": [],
        "ticket_form_id": 360005563896,
        "brand_id": 360000535196,
        "allow_channelback": False,
        "allow_attachments": True,
    },
]
